Messages:
  prefix: '&7[&aBetterBoxes&7]'
  box-already-exists: '&cA box with this name already exists!'
  created-box: '&aYou created a Box with the name &7%boxName!'
  deleted-box: '&aYou deleted the box &7boxName'
  no-such-box: '&cThere is no box with this name!'
  reloaded: '&aYou reloaded the boxes and the config!'
  box-saved: '&aThe box have been saved!'
  no-such-player: '&cThat player is not offline!'
  wrong-amount: '&cThe amount is not a number!'
  gave-player-box: '&aGave that player a box!'
  received-box: '&aYou received the &7%boxName &abox!'
  changed-box-name: '&aYou changed the box name!'
  changed-box-lore: '&aYou changed the box lore!'
